spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/payment_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: payment-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  cloud:
    gateway:
      routes:

        - id: order-service
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**

        - id: inventory-service
          uri: http://localhost:8082
          predicates:
            - Path=/inventory/**

server:
  port: 8080

outbox:
  scheduler:
    fixed-delay: 5000
resilience4j:

  circuitbreaker:

    instances:

      inventoryService:

        # Open circuit when failure rate >= 50%
        failure-rate-threshold: 50

        # Don't calculate failure rate until
        # at least 10 calls have happened
        minimum-number-of-calls: 10

        # Evaluate the latest 10 calls
        sliding-window-size: 10

        # Stay OPEN for 10 seconds
        wait-duration-in-open-state: 10s

        # Allow 3 test calls in HALF_OPEN
        permitted-number-of-calls-in-half-open-state: 3

        # Automatically move OPEN -> HALF_OPEN
        automatic-transition-from-open-to-half-open-enabled: true

        # Consider calls taking > 2 seconds as slow
        slow-call-duration-threshold: 2s

        # Open if 50% of calls are slow
        slow-call-rate-threshold: 50

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always

  health:
    circuitbreakers:
      enabled: true
  properties:
    spring.json.trusted.packages: "*"